### ISSUE TITLE
End-to-End Scenarios

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#180]
Write down 5 different end to end scenarios to show on demo day.

**Comment by jajimentol** [comment]
Research Assistant Anıl, tries to find articles on lupus. 
- Types "lupus" in search, and sees the results.
- Selects an article from the results list.
- In detail page, he wants to tag two fragments of abstract, one with a wikidata entry, one with a free label.
- Anıl selects a fragment, and tag it with "lupus" wikidata entry.
- Then Anıl selects another fragment, and tags it with "lupus articles" label.
- Anıl now can both see the tags in the article detail screen.
- Anıl heads back to the home page, and sees his recent activities in feed.

**Comment by emrecalik** [comment]
Can Dayan and Emre Çalık are medical doctors. When Can was an intern, he read many articles published by Emre and found them very helpful. Since then, Can has tried not to miss any update about Emre.

| # | Step                                      | Expected Behaviour   | 
|---|-------------------------------------------|----------------------|
| 1 | Enter the url of http://34.159.77.79:8000/.                          | Login page is shown. | 
| 2 | Enter username and password. Click login. | Home page is shown.|  
| 3 | Check "Suggested User" part of "Suggestions For You" section.    | "Emre Çalık" is shown as one of suggested users.      | 
| 4 | Click "Emre Çalık".    | User details page is shown.    | User details page is shown.   | 
| 5 | Click "Recent Activities" tab on user details page.    | Emre Çalık's activities are shown.      |  
| 6 | Click "Tagged Articles" tab on user details page.     | Emre Çalık's tagged articles are shown.       |  
| 7 | Click "Follow" button.     | Button is re-rendered as "Unfollow".      |   
| 8 | Click "Home" on header.     | Home page is shown.       |   
| 9 | Check "Feed For You" section.     | "Can Dayan followed Emre Çalık" activity is shown.       |  
| 10 | Check "Suggested User" section.     | Emre Çalık is no longer shown as a suggested user.       |

**Comment by jajimentol** [comment]
| # | Step                                      | Expected Behaviour   | 
|---|-------------------------------------------|----------------------|
| 1 | Enter the home page.                          | Home page is shown with recent activities. | 
| 2 | Type lupus in search, click search. | Lupus results are shown.|  
| 3 | Selects and article from results.    | Article detail page is shown. | 
| 4 | Tag a fragment of article with "lupus" wikidata entry.   | Confirmation window is shown with wikidata data.   | 
| 5 | Anıl confirms tag.    | Article detail page is shown with the new tag.   |  
| 6 | Anıl tags a fragment with "lupus experiment" free text.     | Article detail page is shown with the new tag.    |  
| 7 | Anıl returns to home screen.     | Home screen is shown with updated activity feed and new suggestions.    |

**Comment by semihsolmaz** [comment]
Can Dayan and Emre Çalık are medical doctors. Can is interested in research on POEMs syndrome and uses Wikode to tag articles related to his interest.
Emre is interested in blood protein diseases (which also contains POEMs syndrome as a subclass)

| # | Step                                      | Expected Behaviour   | 
|---|-------------------------------------------|----------------------|
| 1 | Enter the url of http://34.159.77.79:8000/.                          | Login page is shown. | 
| 2 | Enter username and password for Can. Click login. | Home page is shown.|  
| 3 | Search  "POEMs syndrome"  | Articles related to POEMs  syndrome is listed    | 
| 4 | Click on article "Not the final diagnosis: from Addison's disease to POEMS syndrome: a case report and literature review." .    | Article page is shown.    | 
| 5 | Right click on abstract text    | Context menu is popped up.      |  
| 6 | Click on "Tag with wikidata entry"     | Wikidata entry form will be opened on right below corner |  
| 7 | Click on "Search Wikidata Entry"  | Focused in Search Wikidata Entry text input field     |   
| 8 | Enter "POEMs syndrome" in text box and click on Q2553422   | Q2553422 entry is chosen       |   
| 9 | Click on "Tag with wikidata entry"     | Confirm tagging popup  will be opened on right below corner |  
| 10 | Click on "confirm tag"    | New tag will be shown in tag list | 
| 11 | Logout | Login screen will be shown |
| 12 | Enter username and password for Emre. Click login. | Home page is shown.|  
| 13 | Search  "blood protein disease"  | Articles that Can tagged with "POEMs  syndrome" will be listed in search result   |
